[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "python3Packages.setuptools",
  "python3Packages.distutils-extra",
  "python3Packages.wheel"
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
