[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "gfortran",
  "openblas",
  "python3Packages.setuptools",
  "python3Packages.distutils-extra",
  "python3Packages.wheel"
]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-binary=numpy -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
